### ISSUE TITLE
Error: unsupported locale setting

### ISSUE THREAD

**Issue by oldgitdaddy** [provinzio/CoinTaxman#137]
Hi, After pulling the latest changes, I receive the following error:

```
Traceback (most recent call last):
  File "/home/pi/CoinTaxman/src/main.py", line 19, in <module>
    import log_config
  File "/home/pi/CoinTaxman/src/log_config.py", line 20, in <module>
    from config import LOG_LEVEL, TMP_LOG_FILEPATH
  File "/home/pi/CoinTaxman/src/config.py", line 82, in <module>
    locale.setlocale(locale.LC_ALL, locale_str)
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I run a standard config.
Please fix or advice.

**Comment by mjasny** [comment]
Do you have german locales installed on your system?
For example: de_DE.utf-8

**Comment by oldgitdaddy** [comment]
Thanks for the hint. I run CoinTaxman on raspberry pi. This solved the issue:
```
sudo apt update
sudo apt install locales-all
```

**Comment by alexanderadam** [comment]
I ran into the same issue.

Why is the locale needed in the first place?
And maybe it would be easier to give a hint to the user about what to do?

Wouldn't it be easier just to use the current system locale (as every other application does)?

**Comment by provinzio** [comment]
You have good points. 

As a default windows user I never thought of missing locales. Shame on me. 

I am currently not at home and cannot look deeper into the code, but as far as I remember the locale setting is only used for formatting dates with %x.
Therefore, it should be good enough to remove the locale setting and define a config variable `TIME_FORMAT`.
I don't think that we should use the system settings because the tool is there to provide tax calculations for a specific country and I think it's best to stick to the country specific format. 

Looking forward to pull requests.
