### ISSUE TITLE
Support old Kraken statement files

### ISSUE THREAD

**Issue by provinzio** [provinzio/CoinTaxman#18]
The Kraken ledger file changed over the years. While current Kraken users may be able to generate a fresh statement (in the supported format), we could adjust our code, to support old files.

**Comment by wearymanateevedaknotstabooresisting** [comment]
## Experienced Behavior

Trying to import Kraken account statements from 2019 and before results in non-recognition of the Kraken export files.

## Desired Behavior

Kraken account statements should be processable, regardless if they are in pre-2020 format or 2019-and-before-format. The files should be recognized for import and include all ledger entries and trades.

## Possible Reason for Bug

Kraken changed the columns on their account statement export files, adding one additional column in `ledger.csv` as well as `trades.csv`. The additional columns are already respected by `src/book.py` through column names `""` and `"subtype"`. However, they are regarded as required by the code. Therefore, if no all required columns are present, the account statement type is not regarded as valid Kraken file.

## Possible Solution

- Determine, what columns are mandatory for tax calculation of various tax laws.
- Determine, if there are additional, non-mandatory fields in exported account statements of exchanges.
- Minimize imported account statement information to the absolutely required fields for tax calculation.

Another quick fix would be neglecting the `""` and `"subtype"` columns by removing them from `src/book.py` since they are not used anyway, expect for class initialization arguments without functionality with respect to these columns.

### Hint

When importing without those columns, Kraken exchange has another issue finding prices of certain times for certain pairs, see #17.

Valid importing also works by just using a fresh Kraken export. However, users who do not have access to their account anymore can not use their old statements. A work around by inserting new columns may lead to invalid datatypes if not done properly (correct Excel DE/EN configurations, CSV importing and exporting or Python fiddling which may be non-trivial for the common user).

## Attachements

These are `.csv` files, extension is not supported for upload by GitHub, thus using artificial `.txt`. Stupid rule.

- Dummy Columns of old export type from 2019 and before: 
  - [ledgers_2019_before.txt](https://github.com/provinzio/CoinTaxman/files/6095243/ledgers_2019_before.txt)
  - [trades_2019_before.txt](https://github.com/provinzio/CoinTaxman/files/6095245/trades_2019_before.txt)

- Dummy columns of new export type from 2020 up to date:
  - [ledgers_2020_onwards.txt](https://github.com/provinzio/CoinTaxman/files/6095247/ledgers_2020_onwards.txt)
  - [trades_2020_onwards.txt](https://github.com/provinzio/CoinTaxman/files/6095248/trades_2020_onwards.txt)

**Comment by wearymanateevedaknotstabooresisting** [comment]
Please remove the reddit linking, now, with my detailed explanation.

**Comment by wearymanateevedaknotstabooresisting** [comment]
Recognized, that `kraken_trades` actually had a bug in the implementation, since the empty column `""` is not present in todays exports. So only ledgers is affected, with the added `"subtype"` by Kraken.

**Comment by wearymanateevedaknotstabooresisting** [comment]
I went through all my exports and found that the change of ledgers export format, by adding `subtype`, occurred in October 2020.
